# Generated by Django 5.1.2 on 2024-10-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_createpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/imgs/default.jpg', upload_to='Category/imgs/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(default='Posts/imgs/default.jpg', upload_to='Posts/imgs/%y/%m/%d/'),
        ),
    ]
