# Generated by Django 5.1.2 on 2024-10-20 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_image_alter_createpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.time(10, 30)),
            preserve_default=False,
        ),
    ]
