# Generated by Django 5.1.2 on 2024-10-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_createpost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='created_at',
        ),
    ]
