# Generated by Django 5.1.2 on 2024-10-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
